### ISSUE TITLE
Fail at 'run start'

### ISSUE THREAD

**Issue by falkyr** [atSistemas/react-base#86]
Hi all!,

I'm trying to start react-base server after a clean install and I've found some troubles.

I've cloned the respository in local, executed 'sudo npm install' to install all necessary modules and after that I've tried to run de develop server using start script with 'npm run start'.

The first time, it throwed me an error, like '/dist/vender-manifest.json' doesn't exists. After create a void JSON file, I've tried to run the script again and throws me another error I can't idenfity. Seems to be some kind of code problem in one node module.

![react-base](https://cloud.githubusercontent.com/assets/12942742/25843489/c85f87b8-34a7-11e7-84e1-f374c7788143.png)

I'm using Manjaro ( Arch Linux based ).

Can you help me?. Thanks in advance.

**Comment by pmagaz** [comment]
Hi:

React-Base don't need any global dependency so you shouldn't install with sudo. Vendor manifest.json is generated just in postinstall task(npm run generate:dll) to increase build speeds so it seems there was any problem during installation that has blocked the generation of the vendor dll and its manifest.

We had updated dependencies right now. Can you clone again and try a new install?

**Comment by falkyr** [comment]
Hi:

I cloned again and after finish I tried to run 'npm install' but it throws a symlink error and ends.

```
Error: EACCES: permission denied, symlink '/home/.../workspace/react-base/src/base/conf/.react-base/templates/generator-react-base' -> '/usr/lib/node_modules/g
enerator-react-base'
npm ERR!  { Error: EACCES: permission denied, symlink '/home/.../workspace/react-base/src/base/conf/.react-base/templates/generator-react-base' -> '/usr/lib/node_module
s/generator-react-base'
npm ERR!   errno: -13,
npm ERR!   code: 'EACCES',
npm ERR!   syscall: 'symlink',
npm ERR!   path: '/home/.../workspace/react-base/src/base/conf/.react-base/templates/generator-react-base',
npm ERR!   dest: '/usr/lib/node_modules/generator-react-base' }
```
So I have to use 'sudo npm install', all seems to complete fine but no 'dist/manifest.xml' is created running 'npm run start' and I stuck in the same error.

**Comment by falkyr** [comment]
Ok I use 'sudo npm install' and after finish I change propietary of 'node_modules' folder with 'chown'. 

Npm start task still throwing the '/dist' error so I tried with 'npm run build', what creates the 'dist' folder and its content. 

Finally I use 'npm run start' and the develop server starts running without errors, but when I go to 'http://localhost:8000' only shows 'Not found' message.

**Comment by pmagaz** [comment]
It seems it's a permission issue with your Arc Linux because you don't have write permission on this directory because probably  the parent folder was created with sudo and only root can write on it. We have tested the installation in Linux  and OsX with no problems, so if you need to change the node_modules permission you probably have anything wrong....

Try the following:

Be sure you are not logged as root (use "id" command in console to know what user you are)
Create a new folder in your home directory like /home/myuser/react-base
Clone again on this folder without sudo and try npm i without sudo.

**Comment by falkyr** [comment]
Solved!.

I changed the global folder for 'node_modules' from '/usr/lib' to '~/.npm-global' following steps in https://docs.npmjs.com/getting-started/fixing-npm-permissions#option-2-change-npms-default-directory-to-another-directory

Thanks for help!. Time to start with React-Base :)

**Comment by pmagaz** [comment]
You'r welcome :)
